POST http://localhost:3000/transactions/withdraw
Content-Type: application/json

{
    "userId": 7,
    "familyId": 2,
    "accountName": "Ojuri Oluwafemi",
    "accountNumber": "0449541114",
    "bankName": "GTB",
     "amount": 1000
}